devices:
  adjust_period: 10
  capture:
    channels: 2
    device: hw:CARD=Loopback,DEV=1
    format: S24LE
    type: Alsa
  capture_samplerate: 0
  chunksize: 4096
  enable_rate_adjust: true
  enable_resampling: true
  playback:
    channels: 4
    device: hw:CARD=M4
    format: S32LE
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  resampler_type: BalancedAsync
  samplerate: 96000
  silence_threshold: 0
  silence_timeout: 0
  stop_on_rate_change: false
  target_level: 0
filters:
  highpass2k:
    parameters:
      freq: 60
      order: 4
      type: LinkwitzRileyHighpass
    type: BiquadCombo
  lowpass2k:
    parameters:
      freq: 60
      order: 4
      type: LinkwitzRileyLowpass
    type: BiquadCombo
mixers:
  to4chan:
    channels:
      in: 2
      out: 4
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
pipeline:
- name: to4chan
  type: Mixer
- channel: 0
  names:
  - highpass2k
  type: Filter
- channel: 1
  names:
  - highpass2k
  type: Filter
- channel: 2
  names:
  - lowpass2k
  type: Filter
- channel: 3
  names:
  - lowpass2k
  type: Filter
